[package]
name = "turbozone-ui"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
turbozone-core = { path = "../turbozone-core" }

anyhow = { workspace = true }
eframe = { workspace = true }
euclid = { workspace = true }
log = { workspace = true }
smol_str = { workspace = true }
