[package]
name = "turbozone"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

default-run = "turbozone"

[lints]
workspace = true

[dependencies]
turbozone-core = { path = "../turbozone-core" }
turbozone-windows = { path = "../turbozone-windows" }
turbozone-ui = { path = "../turbozone-ui" }

anyhow = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
euclid = { workspace = true }
log = { workspace = true }
smol_str = { workspace = true }

dirs = "6.0.0"
pretty_env_logger = "0.5.0"
