[package]
name = "turbozone-windows"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
turbozone-core = { path = "../turbozone-core" }

anyhow = { workspace = true }
euclid = { workspace = true }
log = { workspace = true }
tap = { workspace = true }
smol_str = { workspace = true }
win32-version-info = "0.3.0"

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
]
