lints = { workspace = true }

[package]
name = "turbozone-windows"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "turbozone"
path = "src/main.rs"

[dependencies]
turbozone-core = { workspace = true }
turbozone-ui = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
eframe = { workspace = true }
euclid = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
smol_str = { workspace = true }
windows = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
