[package]
name = "turbozone-windows"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "turbozone"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
turbozone-core = { path = "../turbozone-core" }
turbozone-ui = { path = "../turbozone-ui" }

anyhow = { workspace = true }
eframe = { workspace = true }
euclid = { workspace = true }
log = { workspace = true }
smol_str = { workspace = true }

clap = { version = "4.6.6", features = ["derive", "env"] }
pretty_env_logger = "0.5.0"
win32-version-info = "0.3.0"

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
]
